function renderSpecial(s,p,index){const b=s.block;
 if(p.route==='/'&&index===0){return `<section class="section hero"><div class="hero-grid"><div><div class="eyebrow">Exhibition lead generation support</div><h1>${esc(s.heading)}</h1><p class="lead">${esc(s.body)}</p><div class="cta-row"><a class="btn primary" href="#/contact/">展示会について相談する</a><a class="btn" href="#/download/">サービス資料を見る</a></div>${wireMeta(s)}</div><div class="visual">[ 展示会現場の実写 / 匿名・顔出しなし ]<br>または構造的なキービジュアル</div></div></section>`}
 if(((p.route.startsWith('/guide/')&&p.route!=='/guide/')&&index===0)||(p.route==='/case/{slug}/'&&index===0)){return `<section class="section"><div class="article-hero"><div class="eyebrow">${esc(p.kind)} / ${esc(p.route)}</div><h1>${esc(s.heading)}</h1><p class="lead">${esc(s.body)}</p><div class="toc"><strong>このページの構成</strong><ol>${p.sections.slice(1).map(x=>`<li>${esc(x.heading==='—'?x.block:x.heading)}</li>`).join('')}</ol></div>${wireMeta(s)}</div></section>`}
 if(b==='選択肢比較'||b==='比較表'||b==='提供範囲の違い'){return `<section class="section">${genericText(s)}${comparisonTable()}${wireMeta(s)}</section>`}
 if(b==='やること / やらないこと'){return `<section class="section">${genericText(s)}<div class="module grid-2"><div class="scope-col"><h3>PATHOSが主に担うこと</h3><ul class="scope-list"><li>展示会当日の声掛け</li><li>来場者との会話・足止め</li><li>名刺 / リード獲得</li><li>社員への引き継ぎ</li></ul></div><div class="scope-col"><h3>主サービスに含めないこと</h3><ul class="scope-list"><li>展示会後のフォローコール</li><li>CRM運用</li><li>展示会後の営業活動一式</li><li>［正式範囲確認後に確定］</li></ul></div></div>${wireMeta(s)}</section>`}
 if(['品質担保','導入フロー','教育・ロープレ','支援内容'].includes(b)){let labels=b==='導入フロー'?['相談','要件確認','準備・教育','展示会当日','報告']:b==='品質担保'?['ヒアリング','対象整理','スクリプト','ロープレ','当日運用']:b==='教育・ロープレ'?['商材共有','対象共有','声掛け確認','ロープレ','当日']:['依頼','確認','準備','当日','振り返り'];return `<section class="section">${genericText(s)}<div class="module steps">${labels.map((x,i)=>`<div class="step"><b>0${i+1} ${x}</b><span>［実運用に合わせて内容確定］</span></div>`).join('')}</div>${wireMeta(s)}</section>`}
 if(b.includes('実績')||b==='成果'||b==='成果・費用対効果'){return `<section class="section">${genericText(s)}<div class="module grid-3"><div class="metric"><small>支援条件</small><div class="num">—</div><small>人数 × 日数</small></div><div class="metric"><small>リード獲得</small><div class="num">—</div><small>定義・条件付き</small></div><div class="metric"><small>継続利用</small><div class="num">—</div><small>期間 / 展示会数</small></div></div><div class="pending">公開可能な一次情報が揃った段階で数値を差し込み。平均保証に見せない。</div>${wireMeta(s)}</section>`}
 if(b==='料金'||b==='PATHOS料金'){return `<section class="section">${genericText(s)}<div class="module price-box"><div><div class="price-main">¥50,000 <small>教育・管理費 / 案件</small></div></div><div><div class="price-main">¥40,000 <small>スタッフ / 名・日</small></div></div></div>${wireMeta(s)}</section>`}
 if(b==='料金シミュレーター'){return `<section class="section">${genericText(s)}<div class="module simulator"><div class="sim-row"><div class="field"><label>スタッフ人数</label><input id="simPeople" type="number" min="1" value="2"></div><div class="field"><label>日数</label><input id="simDays" type="number" min="1" value="3"></div></div><div class="sim-result">概算（仮ロジック）<strong id="simTotal">¥290,000</strong><span>教育・管理費 ¥50,000 + ¥40,000 × 人数 × 日数</span><div class="form-note">※ 最少発注・継続時ルール・追加費用は一次情報確認後に実装。</div></div></div>${wireMeta(s)}</section>`}
 if(b==='FAQ'||b==='FAQ / CTA'){return `<section class="section">${genericText(s)}<div class="module faq">${['何名・何日から依頼できますか？','どのくらい前までに申し込めばよいですか？','どのようなスタッフが担当しますか？','交通費・宿泊費・キャンセルはどうなりますか？'].map(q=>`<div class="faq-item"><div class="faq-q">Q. ${q}</div><div class="faq-a">A. ［実際の運用条件を確認後に回答を掲載］</div></div>`).join('')}</div><div class="cta-row" style="margin-top:24px"><a class="btn primary" href="#/contact/">問い合わせる</a><a class="btn" href="#/download/">資料を見る</a></div>${wireMeta(s)}</section>`}
 if(b==='運営会社 / 担当者'){return `<section class="section">${genericText(s)}<div class="module profile"><div class="person-placeholder">[ 展示会現場 / 後ろ姿・横顔 ]<br>or silhouette / line art</div><div><strong>運営：ブリューエン株式会社</strong><p>展示会支援を担当するメンバーの役割・経験を簡潔に掲載。詳細な会社情報はコーポレートサイトへ。</p><a class="btn" href="#">運営会社について</a></div></div>${wireMeta(s)}</section>`}
 if(b==='最終CTA'||b==='CTA'||b==='サービス導線'){return `<section class="final-cta"><div class="eyebrow">Contact / Download</div><h2>${esc(s.heading)}</h2><p class="lead">${esc(s.body)}</p><div class="cta-row" style="justify-content:center"><a class="btn primary" href="#/contact/">問い合わせる</a><a class="btn" href="#/download/">サービス資料</a></div>${wireMeta(s)}</section>`}
 if(b==='記事一覧'){return `<section class="section">${genericText(s)}<div class="module grid-2"><a class="card" href="#/guide/exhibition-lead-generation/"><div class="placeholder">[ 記事アイキャッチ ]</div><small>実践ガイド</small><strong>展示会のリード獲得数・獲得率を見るときの考え方</strong></a><a class="card" href="#/guide/exhibition-callout/"><div class="placeholder">[ 記事アイキャッチ ]</div><small>実践ガイド</small><strong>展示会の呼び込み・声掛けで重要なポイント</strong></a></div>${wireMeta(s)}</section>`}
 if(b==='事例一覧'){return `<section class="section">${genericText(s)}<div class="module grid-3">${[1,2,3].map((x,i)=>`<a class="card" href="#/case/{slug}/"><div class="placeholder">[ 展示会写真 / ロゴ ]</div><small>導入事例</small><strong>${i===0?'掲載許可後：Loglass等':'事例タイトル'}</strong><div style="font-size:11px;color:#666">課題 / 人数・日数 / 成果条件 / 継続状況</div></a>`).join('')}</div>${wireMeta(s)}</section>`}
 if(b==='3カラムカード'){return `<section class="section">${genericText(s)}<div class="module grid-3">${['導入事例','リード獲得ガイド','呼び込みガイド'].map((x,i)=>`<div class="card"><div class="placeholder">[ ${x} ]</div><small>${i===0?'導入事例':'実践ガイド'}</small><strong>${x}</strong><p style="font-size:11px;color:#666">短い概要テキスト</p></div>`).join('')}</div>${wireMeta(s)}</section>`}
 if(b==='完了メッセージ'){return `<section class="section"><div class="thanks"><div class="eyebrow">Completed</div><h2>${esc(s.heading)}</h2><p class="lead" style="margin-left:auto;margin-right:auto">${esc(s.body)}</p><a class="btn primary" href="#/">TOPへ戻る</a>${wireMeta(s)}</div></section>`}
 if(b==='TOPへ戻る'){return `<section class="section" style="padding-top:28px;padding-bottom:28px;text-align:center"><a class="btn" href="#/">TOPへ戻る</a>${wireMeta(s)}</section>`}
 if(b==='関連コンテンツ導入'){return `<section class="section">${genericText(s)}${wireMeta(s)}</section>`}
 if(b==='フォーム'){let dl=p.route==='/download/';return `<section class="section">${genericText(s)}<form class="module form" onsubmit="event.preventDefault()"><div class="field"><label>会社名 *</label><input placeholder="株式会社〇〇"></div><div class="grid-2"><div class="field"><label>お名前 *</label><input placeholder="山田 太郎"></div><div class="field"><label>メールアドレス *</label><input placeholder="name@example.com"></div></div>${dl?'':`<div class="grid-2"><div class="field"><label>展示会名 / 開催時期</label><input placeholder="例：〇〇EXPO / 10月"></div><div class="field"><label>希望人数</label><select><option>未定</option><option>1名</option><option>2名</option><option>3名以上</option></select></div></div><div class="field"><label>相談内容</label><textarea placeholder="決まっている範囲でご記入ください"></textarea></div>`}<div class="field"><label><input type="checkbox" style="width:auto"> プライバシーポリシーに同意する</label></div><button class="btn primary" type="submit">${dl?'資料をダウンロード':'送信する'}</button></form>${wireMeta(s)}</section>`}
 if(b==='補足'||b==='同意'||b==='送信後'){return `<section class="section" style="padding-top:36px;padding-bottom:36px">${genericText(s)}${wireMeta(s)}</section>`}
 if(b==='立ち位置'){return `<section class="section">${genericText(s)}<div class="module diagram"><span class="walker a">来場者</span><span class="walker b">来場者</span><span class="walker c">来場者</span><div class="booth">展示ブース</div><span class="staff-pin">呼び込み担当</span><span class="employee-pin">説明・商談担当</span></div>${wireMeta(s)}</section>`}
 if(b==='声掛け例'){return `<section class="section">${genericText(s)}<div class="module dialogue"><div class="bubble staff">スタッフ：［実スクリプト確認後に掲載］</div><div class="bubble visitor">来場者：反応 / 質問</div><div class="bubble staff">スタッフ：条件確認 → 社員へ引き継ぎ</div></div>${wireMeta(s)}</section>`}
 if(b==='NG例'){return `<section class="section">${genericText(s)}<div class="module grid-3"><div class="card"><strong>長い説明から入る</strong><p>最初の接点で情報量を増やしすぎない。</p></div><div class="card"><strong>通路をふさぐ</strong><p>来場者導線・会場ルールに配慮。</p></div><div class="card"><strong>同じ声掛けを続ける</strong><p>反応や対象に応じて使い分け。</p></div></div>${wireMeta(s)}</section>`}
 if(b==='社員への引継ぎ'){return `<section class="section">${genericText(s)}<div class="module steps">${['声掛け','反応確認','条件確認','社員を選定','引き継ぎ'].map((x,i)=>`<div class="step"><b>0${i+1} ${x}</b><span>${i===4?'詳しい説明・商談へ':'判断基準を事前共有'}</span></div>`).join('')}</div>${wireMeta(s)}</section>`}
 if(b==='指標の定義'){return `<section class="section">${genericText(s)}<div class="module grid-3"><div class="card"><strong>名刺交換数</strong><p>接点数として扱う場合</p></div><div class="card"><strong>リード数</strong><p>企業ごとの定義を明示</p></div><div class="card"><strong>有効リード数</strong><p>条件を満たす対象のみ</p></div></div>${wireMeta(s)}</section>`}
 if(b==='目安・ベンチマーク'){return `<section class="section">${genericText(s)}<div class="module grid-2"><div class="card"><strong>公開データ</strong><div class="placeholder">[ 出典付きベンチマーク ]</div><p>展示会・業種・調査条件を明記。</p></div><div class="card"><strong>PATHOS実測</strong><div class="placeholder">[ 展示会別・人日別データ ]</div><p>分母・リード定義・条件を明記。</p></div></div>${wireMeta(s)}</section>`}
 if(b==='成果を左右する要因'){return `<section class="section">${genericText(s)}<div class="module grid-3">${['来場者 / 展示会','ブース位置','商材との相性','スタッフ人数','声掛け方法','社員への引継ぎ'].map(x=>`<div class="card"><strong>${x}</strong><p>複数条件を合わせて評価</p></div>`).join('')}</div>${wireMeta(s)}</section>`}
 if(b==='増やす方法'){return `<section class="section">${genericText(s)}<div class="module steps">${['定義・目標','対象','配置','声掛け','記録・改善'].map((x,i)=>`<div class="step"><b>0${i+1} ${x}</b><span>実務に落とせる粒度で整理</span></div>`).join('')}</div>${wireMeta(s)}</section>`}
 if(b==='声をかける相手'){return `<section class="section">${genericText(s)}<div class="module checklist">${['ブースに視線を向けている','足を緩めている / 立ち止まる','対象業種・役職の条件に合う','社員へ引き継ぐ条件を満たす'].map(x=>`<div class="check">${x}</div>`).join('')}</div><div class="pending">実際の判断基準はPATHOSの現場ルール確認後に置換。</div>${wireMeta(s)}</section>`}
 if(b==='自社社員'||b==='一般コンパニオン / 説明員'||b==='展示会営業代行'||b==='PATHOS'){return `<section class="section">${genericText(s)}<div class="module grid-2"><div class="card"><strong>向いているケース</strong><p>この選択肢が合う条件を簡潔に整理。</p></div><div class="card"><strong>確認したい点</strong><p>対応範囲・事前準備・当日役割・展示会後の対応を確認。</p></div></div>${wireMeta(s)}</section>`}
 if(b==='選び方'){return `<section class="section">${genericText(s)}<div class="module checklist">${['展示会当日の人手が足りない','社員を商品説明・商談に集中させたい','展示会後の営業代行までは不要','呼び込み・リード獲得を外部化したい'].map(x=>`<div class="check">${x}</div>`).join('')}</div>${wireMeta(s)}</section>`}
 if(b==='発注例'||b==='最低発注額・他サービス比較'){return `<section class="section">${genericText(s)}<div class="module grid-3"><div class="card"><strong>1名 × 1日</strong><div class="placeholder">［最少発注確認後］</div><p>体制イメージ</p></div><div class="card"><strong>2名 × 3日</strong><div class="placeholder">概算 ¥290,000</div><p>教育・管理費を含む仮算出</p></div><div class="card"><strong>その他</strong><div class="placeholder">人数 × 日数</div><p>用途に合わせて算出</p></div></div>${wireMeta(s)}</section>`}
 if(b==='一般的な費用相場'){return `<section class="section">${genericText(s)}<div class="module grid-3"><div class="card"><strong>日当</strong><div class="placeholder">[ 公開料金調査後 ]</div></div><div class="card"><strong>事前研修 / 手配</strong><div class="placeholder">[ 含有・別途を整理 ]</div></div><div class="card"><strong>総額</strong><div class="placeholder">[ 条件別に比較 ]</div></div></div>${wireMeta(s)}</section>`}
 if(b==='追加費用・発注条件'){return `<section class="section">${genericText(s)}<div class="module grid-4">${['交通費 / 宿泊費','時間超過','キャンセル','申込期限 / オプション'].map(x=>`<div class="card"><strong>${x}</strong><p>［正式条件確認後］</p></div>`).join('')}</div>${wireMeta(s)}</section>`}
 if(b==='資料内容'){return `<section class="section">${genericText(s)}<div class="module grid-3">${['サービス概要・対応範囲','料金・導入事例','利用の流れ・FAQ'].map(x=>`<div class="card"><div class="placeholder">[ 資料ページ ]</div><strong>${x}</strong></div>`).join('')}</div>${wireMeta(s)}</section>`}
 if(b==='FV'&&p.route==='/download/'){return `<section class="section hero"><div class="hero-grid"><div>${genericText(s)}<a class="btn primary" href="#form">資料をダウンロード</a>${wireMeta(s)}</div><div class="visual">[ サービス資料 表紙 / モックアップ ]</div></div></section>`}
 if(p.route==='/privacy/'){return `<section class="section"><div class="article">${genericText(s)}<div class="placeholder" style="height:70px">［正式な法務本文 / 実装内容に合わせて確定］</div>${wireMeta(s)}</div></section>`}
 if(b==='導入前の課題'||b==='検討プロセス'||b==='顧客コメント'){return `<section class="section">${genericText(s)}<div class="module grid-2"><div class="card"><strong>取材内容</strong><p>［顧客インタビューから事実ベースで掲載］</p></div><div class="card"><strong>公開条件</strong><p>企業・本人の許諾範囲に限定。</p></div></div>${wireMeta(s)}</section>`}
 return `<section class="section">${genericText(s)}<div class="module visual" style="min-height:160px">[ ${esc(s.block)} の図表 / 画像 / UI領域 ]</div>${wireMeta(s)}</section>`;
}
function globalHeader(p){return `<div class="browser-chrome"><span class="dot"></span><span class="dot"></span><span class="dot"></span><div class="address">https://pathos.bluhen.org${esc(p.route)}</div></div><header class="site-header"><a class="logo" href="#/">PATHOS</a><nav class="site-nav"><a href="#/">サービス</a><a href="#/price/">料金</a><a href="#/compare/">比較</a><a href="#/guide/">実践情報</a><a href="#/case/">導入事例</a></nav><div class="site-actions"><a class="btn" href="#/download/">資料DL</a><a class="btn primary" href="#/contact/">問い合わせ</a></div></header><div class="page-meta"><span class="route-badge">${esc(p.route)}</span><span>${esc(p.name)}</span><span>${esc(p.kind)}</span><span>source: ${esc(p.sheet)}</span></div>`}
function footer(){return `<footer class="site-footer"><div class="footer-grid"><div><div class="footer-logo">PATHOS</div><div style="margin-top:10px;color:#999">展示会当日の呼び込み・リード獲得支援</div></div><div class="footer-col"><strong>Service</strong><a href="#/">TOP</a><a href="#/price/">料金</a><a href="#/compare/">比較</a></div><div class="footer-col"><strong>Contents</strong><a href="#/guide/">実践情報</a><a href="#/case/">導入事例</a><a href="#/download/">資料DL</a></div><div class="footer-col"><strong>Company</strong><a href="#/contact/">問い合わせ</a><a href="#/privacy/">プライバシー</a></div></div></footer>`}
function render(){let route=decodeURIComponent(location.hash.slice(1))||'/';if(!pageByRoute[route]) route='/';const p=pageByRoute[route];document.querySelectorAll('.page-link').forEach(a=>a.classList.toggle('active',a.dataset.route===route));let inner=p.sections.map((s,i)=>renderSpecial(s,p,i)).join('');document.getElementById('browser').innerHTML=globalHeader(p)+`<div class="page ${((p.route.startsWith('/guide/')&&p.route!=='/guide/')||p.route==='/case/{slug}/')?'article':''}">${inner}</div>`+footer();bindSim();window.scrollTo({top:0,behavior:'instant'});}
function bindSim(){const pe=document.getElementById('simPeople'),da=document.getElementById('simDays'),to=document.getElementById('simTotal');if(!pe||!da||!to)return;const calc=()=>{const v=50000+40000*Math.max(1,+pe.value||1)*Math.max(1,+da.value||1);to.textContent='¥'+v.toLocaleString('ja-JP')};pe.addEventListener('input',calc);da.addEventListener('input',calc);calc();}
const nav=document.getElementById('pageNav');nav.innerHTML=pages.map(p=>`<a class="page-link" data-route="${esc(p.route)}" href="#${encodeURI(p.route)}">${esc(p.name)}<small>${esc(p.route)}</small></a>`).join('');
window.addEventListener('hashchange',render);render();
const metaBtn=document.getElementById('metaToggle');metaBtn.addEventListener('click',()=>{document.body.classList.toggle('show-meta');metaBtn.classList.toggle('active');metaBtn.textContent=document.body.classList.contains('show-meta')?'構成メモを隠す':'構成メモを表示';});
